services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: skillflow_db
      POSTGRES_USER: skillflow_user
      POSTGRES_PASSWORD: aa33!!gHjQ702J4
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
